# Generated by Django 5.2.6 on 2025-09-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_munji', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='RiceProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dryer_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factory_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quality_of_rice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rice_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_quality', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('naku_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('naku_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunjiPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('total_bags', models.PositiveIntegerField()),
                ('buying_quantity_munji', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_munji_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('munji_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munji_app.supplier')),
            ],
        ),
    ]
