# Generated by Django 5.2.6 on 2025-09-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munji_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='munjipurchase',
            name='total_munji_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='payment_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munji_app.category'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('munji_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='munji_app.munjipurchase')),
            ],
        ),
    ]
