# Generated by Django 5.2.1 on 2025-10-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munji_app', '0002_category_munjipurchase_total_munji_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={},
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='munji_app.category'),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='munji_app.supplier'),
        ),
        migrations.AlterField(
            model_name='munjipurchase',
            name='total_munji_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
