# Generated by Django 5.2.1 on 2025-12-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munji_app', '0004_category_created_at_globalsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneouscost',
            name='type',
            field=models.CharField(blank=True, choices=[('miscellaneous', 'miscellaneous'), ('perpit', 'perpit')], max_length=15, null=True),
        ),
    ]
